
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4001:4000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PG_CONNECTION_URI=postgres://mesuser:mespass@db:5432/mesdb
      - PORT=4000
  
  db:
    image: postgres:16.3-alpine3.20
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~/apps/mes-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mespass
      - POSTGRES_USER=mesuser
      - POSTGRES_DB=mesdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
